version: 2

sources:
  - name: french_towns
    schema: main
    tables:
      - name: communes_france
        meta:
          external_location: "ST_Read('{{ var('input_dir') }}/communes_france.geojson')"

      - name: arrondissements
        meta:
          external_location: "read_csv_auto('{{ var('input_dir') }}/arrondissements.csv')"

      - name: departements
        meta:
          external_location: "read_csv_auto('{{ var('input_dir') }}/departements.csv')"

      - name: populations_historiques
        meta:
          external_location: "read_csv_auto('{{ var('input_dir') }}/DS_POPULATIONS_HISTORIQUES_data.csv', sample_size=-1)"


      - name: salaries
        meta:
          external_location: "read_csv_auto('{{ var('input_dir') }}/DS_BTS_SAL_EQTP_SEX_PCS_2023_data.csv', sample_size=-1)"
