services:
  polaris:
    image: apache/polaris:latest
    container_name: polaris-lakehouse
    ports:
      - "8181:8181"
    environment:
      CLIENT_ID: ${POLARIS_CLIENT_ID}
      CLIENT_SECRET: ${POLARIS_CLIENT_SECRET}
      POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,${POLARIS_CLIENT_ID},${POLARIS_CLIENT_SECRET}
      POLARIS_FEATURES_ALLOW_SETTING_S3_ENDPOINTS: "true"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: us-east-1
      POLARIS_PERSISTENCE_TYPE: relational-jdbc
      QUARKUS_DATASOURCE_USERNAME: french_towns
      QUARKUS_DATASOURCE_PASSWORD: ${POLARIS_DB_PASSWORD}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-lakehouse:5432/polaris_meta
    networks:
      - lakehouse-net
    restart: unless-stopped

networks:
  lakehouse-net:
    external: true
    name: docker_lakehouse-net
